name: deploy
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
env:
  AWS_REGION: ap-northeast-1
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: |
          yarn --frozen-lockfile
      - run: |
          yarn cdk deploy \
            -c slackBotToken=${{ secrets.SLACK_BOT_TOKEN }} \
            -c slackSigningSecret=${{ secrets.SLACK_SIGNING_SECRET }} \
            -c knowledgeBaseId=${{ secrets.KNOWLEDGE_BASE_ID }} \
            -c dataSourceId=${{ secrets.DATA_SOURCE_ID }} \
            -c dataSourceBucketName=${{ secrets.DATA_SOURCE_BUCKET_NAME }} \
            -c modelArn=${{ secrets.MODEL_ARN }} \
            -c githubRepo=${{ github.repository }} \
            --require-approval never \
            --all
